# specify additional collections, similar to posts
collections:
  authors:
    output: true

# specify any default front matter variables
# e.g. which layout to use from the _layouts dir
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag